[env:mi_placa_yd_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Puertos
upload_port = COM4
monitor_port = COM4

; Forzamos Flash y PSRAM
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

; --- SOLUCIÓN PARA EVITAR QUE SE CUELGUE EL MONITOR EN UART ---
; monitor_dtr = 0   ; <--- Comentados para que el UART funcione bien
; monitor_rts = 0   ; <--- Comentados para que el UART funcione bien

; --- BANDERAS DE COMPILACIÓN (Configuradas para puerto COM/UART) ---
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0   ; Salida de texto por el puerto UART
    -DARDUINO_USB_MODE=0

; --- LIBRERÍAS ---
lib_deps =
    knolleary/PubSubClient @ ^2.8.0
    pololu/QTRSensors @ ^4.0.0
    mikalhart/TinyGPSPlus @ ^1.0.3