[env:mi_placa_yd_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Puertos (Asegúrate de que siga siendo COM4 en tu PC)
upload_port = COM4
monitor_port = COM4

; Forzamos los 16MB de Flash y los 8MB de PSRAM
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

; --- SOLUCIÓN PARA EVITAR QUE SE CUELGUE EL MONITOR ---
monitor_dtr = 0
monitor_rts = 0

; --- BANDERAS DE COMPILACIÓN ---
build_flags = 
    -DBOARD_HAS_PSRAM             ; Habilita físicamente el uso de la PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0   ; '0' para usar el puerto UART (el que tienes conectado ahora)
    ; -DARDUINO_USB_MODE=1        ; (Comentado para evitar bugs de terminal)

; --- LIBRERÍAS ---
lib_deps =
    knolleary/PubSubClient @ ^2.8.0