[env:mi_placa_yd_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Puerto USB nativo
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

; Configuración de flash y PSRAM
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

; Flags de compilación
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1   ; Activar USB CDC nativo para upload y monitor
    -DARDUINO_USB_MODE=1          ; Usar USB nativo

; Librerías
lib_deps =
    knolleary/PubSubClient @ ^2.8.0
    pololu/QTRSensors @ ^4.0.0
    mikalhart/TinyGPSPlus @ ^1.0.3